'use client';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import NavBar from "@/components/Navbar";
import { usePathname } from "next/navigation";
import { useEffect } from "react";
// import LanguageSwitcher from '@/components/LanguageSwitcher';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Test Next.js App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const showNavBar = !pathname?.startsWith("/banka");
  useEffect(() => {
    if (pathname?.startsWith("/banka")) {
      document.title = "Banka";
    } else {
      document.title = "Prodavnica Web";
    }
  }, [pathname]);
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {showNavBar && <NavBar />}
          {children}
        </Providers>
      </body>
    </html>
  );
}
