
import type { Metadata } from "next";

import NavBar from "./NavBar";


export const metadata: Metadata = {
    title: "Banka App",
    description: "Generated by create next app",
};

export default function BankaLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <NavBar />
            {children}
        </>
    );
}
